### PR TITLE
configuring ESLint & Prettier for NextJS UniUp Website

### PR DESCRIPTION
**Pull request by souibguimohamed**

### CODE REVIEW

**Comment by houssemAmiri** [comment]
Task linked: [CU-3j8j8nc add eslint and prettier to website-uniup](https://app.clickup.com/t/3j8j8nc)

**Comment by souibguimohamed** [comment]
I'd like to emphasize the importance of grouping all commits into a single one; it will look more professional.

**Review by houssemAmiri — APPROVED** [review]

**Comment by houssemAmiri** [comment]
@souibguimohamed  pleas add the tutorial link in the PR comments

**Comment by souibguimohamed** [comment]
here it is @houssemAmiri : https://youtu.be/clU3zb48BtI

**Pull request merged**
